/* Compact studio interactions and easy catalogue discovery. */
let pictureQuery='';
const TAB_ICONS={stories:'📖',characters:'⭐',scene:'🌳',animal:'🐻',cartoon:'🌈',building:'🏰',people:'🧑',comic:'💬',featured:'✨'};
const CHARACTER_SEARCH={'character-shinchan':'蜡笔小新 Shinchan','character-mickey':'米奇 Mickey Disney 迪士尼','character-doraemon':'哆啦A梦 小叮当 机器猫 Doraemon','character-garfield':'加菲猫 咖啡猫 Garfield','character-donald':'唐老鸭 Donald Disney 迪士尼','character-woody':'胡迪 Woody Toy Story 玩具总动员','character-buzz':'巴斯光年 Buzz Toy Story 玩具总动员','character-spiderman':'蜘蛛侠 Spider Man Marvel 漫威','character-ironman':'钢铁侠 Iron Man Marvel 漫威'};
function picturesForSelection(cat,lv){return pictureQuery.trim()?CATS.flatMap(c=>LIST[c.id+lv]):LIST[cat.id+lv]}
function matchesPictureQuery(p){const words=pictureQuery.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean),text=(p.name+' '+(p.searchTerms||'')+' '+(CHARACTER_SEARCH[p.id]||'')).toLocaleLowerCase();return words.every(word=>text.includes(word))}
const searchRender=renderPick;renderPick=function(){searchRender();$('difficultySelect').value=String(ui.lv);$('pictureSearch').value=pictureQuery;[...$('tabs').children].forEach((tab,i)=>{const cat=CATS[i];tab.textContent=(TAB_ICONS[cat.id]||'🎨')+' '+cat.name;tab.setAttribute('aria-label',cat.name);const prior=tab.onclick;tab.onclick=event=>{pictureQuery='';clearTimeout(searchDelay);prior(event)}});const empty=$('grid').querySelector('.empty-gallery');if(empty&&pictureQuery)empty.textContent='🔎 这个难度还没有找到「'+pictureQuery+'」，试试其他难度或换个关键词。';$('galleryHint').textContent=onlyMyArt?'你画过的作品都在这里':'选主题和难度，或输入喜欢的角色名字。'};
let searchDelay=null;$('pictureSearch').oninput=()=>{clearTimeout(searchDelay);pictureQuery=$('pictureSearch').value.slice(0,60);pickPageLimit=12;searchDelay=setTimeout(renderPick,140)};$('difficultySelect').onchange=()=>{ui.lv=Number($('difficultySelect').value)||1;pickPageLimit=12;saveUi();renderPick()};
const experienceShow=show;show=function(id){experienceShow(id);document.documentElement.classList.toggle('studio-active',id==='color');if(id==='scr-cover')refreshResume()};
const saveResume=refreshResume;refreshResume=function(){saveResume();const last=load(KEY+'-last',null),p=last?pictureById(last):null;if(p&&!$('resumeArt').hidden){$('resumeArt').textContent='🖍 继续上次创作 · '+(artFor(p.id).title||p.name);$('resumeArt').title='继续 '+(artFor(p.id).title||p.name)}};$('coverStart').after($('resumeArt'));refreshResume();
$('finClose').onclick=()=>{closeFinish();$('doneBtn').focus({preventScroll:true})};
let touchFill=false,lastFillStart=null;canvas.addEventListener('pointerdown',e=>{touchFill=e.pointerType==='touch';lastFillStart=['fill','erase'].includes(tool)?{x:e.clientX,y:e.clientY,id:e.pointerId}:null},{capture:true});canvas.addEventListener('pointermove',e=>{if(lastFillStart?.id===e.pointerId&&Math.hypot(e.clientX-lastFillStart.x,e.clientY-lastFillStart.y)>9)suppressCanvasClick=Date.now()+650},{capture:true});canvas.addEventListener('pointercancel',()=>{lastFillStart=null;suppressCanvasClick=Date.now()+400},{capture:true});
function pickFillRegion(e){const direct=e.target.closest?.('.r');if(!touchFill&&e.pointerType!=='touch')return direct;if(direct&&!direct.classList.contains('paint-background'))return direct;const radius=8,candidates=[];for(const r of regions){if(r.classList.contains('paint-background'))continue;const box=r.getBoundingClientRect();if(!box.width||!box.height||Math.min(box.width,box.height)>20)continue;const dx=Math.max(box.left-e.clientX,0,e.clientX-box.right),dy=Math.max(box.top-e.clientY,0,e.clientY-box.bottom);if(Math.hypot(dx,dy)>radius)continue;let precise=true;if(typeof r.isPointInFill==='function'&&typeof r.getScreenCTM==='function'){try{const matrix=r.getScreenCTM()?.inverse();if(matrix){const point=canvas.createSVGPoint();point.x=Math.max(box.left+.2,Math.min(box.right-.2,e.clientX));point.y=Math.max(box.top+.2,Math.min(box.bottom-.2,e.clientY));precise=r.isPointInFill(point.matrixTransform(matrix));}}catch{precise=false}}if(precise)candidates.push({r,d:Math.hypot(dx,dy)+Math.hypot(e.clientX-(box.left+box.width/2),e.clientY-(box.top+box.height/2))*.02})}candidates.sort((a,b)=>a.d-b.d);return candidates[0]?.r||direct}
function paintFeedback(el,e){if(!reduce){el.classList.remove('paint-pop');void el.getBoundingClientRect();el.classList.add('paint-pop');setTimeout(()=>el.classList.remove('paint-pop'),380)}if((touchFill||e.pointerType==='touch')&&typeof navigator.vibrate==='function')navigator.vibrate(8)}
// Follow device motion preferences without exposing another settings panel.
const deviceMotion=matchMedia('(prefers-reduced-motion: reduce)');deviceMotion.addEventListener?.('change',e=>{playgroundPrefs.reduceMotion=e.matches;applyPreferences()});

WORLD_DEFS.push({id:'dinosaurs',name:'恐龙王国',emoji:'🦖',color:'#e0f0c8',match:/恐龙|抱抱龙|耀西|三角龙|霸王龙|剑龙|翼龙/,task:'为恐龙朋友创造一个神奇世界'},{id:'characters',name:'卡通明星',emoji:'⭐',color:'#fff0c2',cat:'characters',match:/.*/,task:'给你喜欢的卡通角色设计新的色彩'});
