// Optional local artist profile; signatures are saved with each artwork.
let artistProfile=Object.assign({name:''},load(KEY+'-artist',{}));
const cleanArtistName=value=>Array.from(String(value||'').replace(/[\u0000-\u001F\u007F]/g,'').trim()).slice(0,20).join('');
artistProfile.name=cleanArtistName(artistProfile.name);
function signatureFor(id){const a=artFor(id);return a.showSignature===false?'':cleanArtistName(a.artistName===undefined?artistProfile.name:a.artistName)}
function refreshArtist(){ $('artistName').value=artistProfile.name;$('artistWelcome').textContent=artistProfile.name?artistProfile.name+'，欢迎来到你的彩色世界！':'名字只保存在这台设备，不需要注册。';if(cur){$('artArtist').value=artFor(cur.id).artistName===undefined?artistProfile.name:artFor(cur.id).artistName;$('showSignature').checked=artFor(cur.id).showSignature!==false}}
$('artistForm').onsubmit=e=>{e.preventDefault();artistProfile.name=cleanArtistName($('artistName').value);if(!save(KEY+'-artist',artistProfile)){toast('名字暂时没能保存，可以直接在作品上填写');return}refreshArtist();toast(artistProfile.name?'欢迎你，'+artistProfile.name+'！':'名字已清空，随时可以再填写')};
$('artArtist').onchange=()=>{if(!cur)return;artFor(cur.id).artistName=cleanArtistName($('artArtist').value);$('artArtist').value=artFor(cur.id).artistName;saveState()};$('showSignature').onchange=()=>{if(cur){artFor(cur.id).showSignature=$('showSignature').checked;saveState()}};
/* KidPaint: accessible studio, dependable local storage, worlds and offline use. */
const cloneData=value=>JSON.parse(JSON.stringify(value));
let playgroundPrefs=Object.assign({reduceMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,largeButtons:true,colorNames:true},load(KEY+'-accessibility',{}));
const COLOR_NAMES={'#FF4D6D':'玫红','#FF8C2E':'橙色','#FFD23F':'黄色','#2BD48F':'绿色','#2EB6FF':'天蓝','#4D6BFF':'蓝色','#9B5CFF':'紫色','#FFFFFF':'白色','#2A1B5E':'深紫'};
const QUICK_COLORS=Object.keys(COLOR_NAMES);
function applyPreferences(){reduce=!!playgroundPrefs.reduceMotion;document.documentElement.classList.toggle('quiet-motion',reduce);document.documentElement.classList.toggle('large-controls',!!playgroundPrefs.largeButtons);document.documentElement.classList.toggle('named-colors',!!playgroundPrefs.colorNames);if(reduce)stopCelebration();$('reduceMotion').checked=reduce;$('largeButtons').checked=playgroundPrefs.largeButtons;$('colorNames').checked=playgroundPrefs.colorNames;renderQuickColors()}
function renderQuickColors(){const host=$('quickColors');host.replaceChildren();QUICK_COLORS.forEach(c=>{const b=document.createElement('button');b.className='quick-color';b.style.setProperty('--swatch',c);b.setAttribute('aria-label',COLOR_NAMES[c]);b.setAttribute('aria-pressed',String(color===c));b.title=COLOR_NAMES[c];b.innerHTML='<i aria-hidden="true"></i><span>'+COLOR_NAMES[c]+'</span>';b.onclick=()=>{color=c;if(!['brush','rainbow','gradient'].includes(tool))setTool('fill');renderDock();renderQuickColors();SFX.select()};host.appendChild(b)})}
const originalPickColor=pick2;pick2=function(c){const prior=tool;originalPickColor(c);if(['rainbow','gradient'].includes(prior))setTool(prior);renderQuickColors()};
const originalSetTool=setTool;setTool=function(t){if(t==='brush'||t==='rainbow'||t==='gradient'){if(layerState(cur?.id).paint.locked){toast('画笔图层锁住了，先解锁再画吧');return}}if(t==='sticker'&&layerState(cur?.id).stickers.locked){toast('贴纸图层锁住了，先解锁再调整吧');return}originalSetTool(t);['Rainbow','Gradient'].forEach(n=>$('t'+n).setAttribute('aria-pressed',String(t===n.toLowerCase())));renderQuickColors()};
$('tRainbow').onclick=()=>setTool('rainbow');$('tGradient').onclick=()=>setTool('gradient');
['reduceMotion','largeButtons','colorNames'].forEach(id=>$(id).onchange=()=>{playgroundPrefs[id==='reduceMotion'?'reduceMotion':id]= $(id).checked;save(KEY+'-accessibility',playgroundPrefs);applyPreferences()});
let settingsReturn=null,guideReturn=null;
function openSettings(){settingsReturn=document.activeElement;$('settings').hidden=false;$('settingsClose').focus()}
function closeSettings(){$('settings').hidden=true;settingsReturn?.focus()}
function openGuide(){guideReturn=document.activeElement;$('guide').hidden=false;$('guideClose').focus()}
function closeGuide(){save(KEY+'-guided',true);$('guide').hidden=true;guideReturn?.focus()}
$('settingsOpen').onclick=openSettings;$('settingsClose').onclick=closeSettings;$('guideOpen').onclick=$('guideFromSettings').onclick=openGuide;$('guideClose').onclick=closeGuide;
$('settings').onclick=e=>{if(e.target===$('settings'))closeSettings()};$('guide').onclick=e=>{if(e.target===$('guide'))closeGuide()};
addEventListener('keydown',e=>{const modal=!$('guide').hidden?$('guide'):!$('settings').hidden?$('settings'):null;if(!modal)return;if(e.key==='Escape'){e.preventDefault();modal.id==='guide'?closeGuide():closeSettings()}if(e.key==='Tab'){const nodes=[...modal.querySelectorAll('button,input,select,[tabindex="0"]')].filter(el=>!el.hidden&&!el.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function layerState(id){if(!id)return {drawing:{visible:true,locked:false},paint:{visible:true,locked:false},stickers:{visible:true,locked:false}};const a=artFor(id);if(!a.layers)a.layers={drawing:{visible:true,locked:false},paint:{visible:true,locked:false},stickers:{visible:true,locked:false}};return a.layers}
function drawingLocked(){return !!cur&&layerState(cur.id).drawing.locked}
function rememberState(){return {fills:regions.map(el=>el.getAttribute('fill')),art:cloneData(artFor(cur.id))}}
function snapshotFull(){redoStack=[];history.push({full:rememberState()});updateUndo()}
function applyHistory(h,destination){if(h.full){destination.push({full:rememberState()});creative[cur.id]=cloneData(h.full.art);regions.forEach((el,i)=>el.setAttribute('fill',h.full.fills[i]||WHITE))}else if(h.art){destination.push({art:cloneData(artFor(cur.id))});creative[cur.id]=cloneData(h.art)}else{destination.push([h[0],regions[h[0]].getAttribute('fill')]);regions[h[0]].setAttribute('fill',h[1])}selectedSticker=null;decorateSvg($('canvas'),cur.id);saveState();progress();updateUndo();syncStickerControls();renderLayerControls()}
$('undo').onclick=()=>{const h=history.pop();if(h)applyHistory(h,redoStack)};$('redo').onclick=()=>{const h=redoStack.pop();if(h)applyHistory(h,history)};
const baseResetConfirm=resetConfirm;resetConfirm=function(on){baseResetConfirm(on);if(on)$('resetYes').onclick=()=>{snapshotFull();const previous=artFor(cur.id);regions.forEach(el=>el.setAttribute('fill',WHITE));creative[cur.id]={paths:[],stickers:[],title:previous.title,layers:cloneData(layerState(cur.id))};selectedSticker=null;done=false;commitArt();progress();renderLayerControls();resetConfirm(false)}};
let savedTime=null;
function refreshResume(){const id=load(KEY+'-last',null);$('resumeArt').hidden=!id||!pictureById(id)||!hasArtwork(id)}
saveState=function(){if(!cur)return;store[cur.id]=regions.map(el=>el.getAttribute('fill'));if(artFor(cur.id).artistName===undefined)artFor(cur.id).artistName=artistProfile.name;const ok=save(KEY+'-snapshot',{store,creative,stars:res});if(ok){save(KEY,store);save(KEY+'-creative',creative);save(KEY+'-last',cur.id);savedTime=new Date();$('saveStatus').textContent='✓ 已自动保存 · '+savedTime.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});$('saveStatus').classList.remove('save-error')}else{$('saveStatus').textContent='作品暂时没能保存，请到小画展导出画册备份';$('saveStatus').classList.add('save-error')}lastBlob=null;refreshResume()};
$('resumeArt').onclick=()=>{const p=pictureById(load(KEY+'-last',null));if(p)openPic(p)};
function layerAttributes(id,layer,interactive){const l=layerState(id)[layer];return (l.visible?'':' style="display:none"')+' pointer-events="'+(interactive&&!l.locked?'auto':'none')+'"'}
artMarkup=function(id,interactive=false){const a=artFor(id),gradientId='rainbow-'+hashStr(id),softId='soft-'+hashStr(id);let defs='<defs><linearGradient id="'+gradientId+'" x1="0" y1="0" x2="400" y2="400" gradientUnits="userSpaceOnUse">'+['#FF4D6D','#FF8C2E','#FFD23F','#2BD48F','#2EB6FF','#4D6BFF','#9B5CFF'].map((c,i)=>'<stop offset="'+i/6+'" stop-color="'+c+'"/>').join('')+'</linearGradient><linearGradient id="'+softId+'" x1="0" y1="0" x2="400" y2="400" gradientUnits="userSpaceOnUse"><stop stop-color="'+esc(a.gradientColor||'#FF4D6D')+'"/><stop offset="1" stop-color="#9B5CFF"/></linearGradient></defs>';
defs+=a.paths.filter(p=>p.mode==='gradient').map(p=>'<linearGradient id="gradient-'+hashStr(id+'|'+p.id)+'" x1="0" y1="0" x2="400" y2="400" gradientUnits="userSpaceOnUse"><stop stop-color="'+esc(p.color)+'"/><stop offset="1" stop-color="#9B5CFF"/></linearGradient>').join('');defs=defs.replace('</defs>','')+'</defs>';
const paths='<g data-artlayer="paint"'+layerAttributes(id,'paint',interactive)+'>'+a.paths.map(p=>'<path data-creative-path="'+esc(p.id)+'" d="'+esc(p.d)+'" fill="none" stroke="'+(p.mode==='rainbow'?'url(#'+gradientId+')':p.mode==='gradient'?'url(#gradient-'+hashStr(id+'|'+p.id)+')':esc(p.color))+'" stroke-width="'+p.width+'" stroke-linecap="round" stroke-linejoin="round"/>').join('')+'</g>';
const stickers='<g data-artlayer="stickers"'+layerAttributes(id,'stickers',interactive)+'>'+a.stickers.map(t=>{const b=B();put(b,t.key,0,0,t.size,false);return '<g data-sticker="'+esc(t.id)+'" transform="translate('+t.x+' '+t.y+') rotate('+(t.rotation||0)+')"'+(interactive&&t.id===selectedSticker?' class="art-selected"':'')+'>'+b.out()+(interactive&&t.id===selectedSticker?'<rect x="'+(-t.size/2-5)+'" y="'+(-t.size/2-5)+'" width="'+(t.size+10)+'" height="'+(t.size+10)+'" fill="none" stroke="#9b5cff" stroke-width="2" stroke-dasharray="5 4" pointer-events="none"/>':'')+'</g>'}).join('')+'</g>';
return defs+(a.layerOrder==='stickers-first'?stickers+paths:paths+stickers)};
const baseDecorate=decorateSvg;decorateSvg=function(svg,id,interactive=svg.id==='canvas'){baseDecorate(svg,id,interactive);const layer=layerState(id).drawing;[svg.querySelector('.paint-background'),svg.querySelector('g[stroke-width="4"]')].forEach(el=>{if(!el)return;el.style.display=layer.visible?'':'none';el.style.pointerEvents=interactive&&!layer.locked?'auto':'none'})};
function renderLayerControls(){const host=$('layerControls');host.replaceChildren();if(!cur)return;Object.entries({drawing:'图画和背景',paint:'自由画笔',stickers:'贴纸'}).forEach(([key,label])=>{const row=document.createElement('div');row.className='layer-row';const title=document.createElement('b');title.textContent=label;row.appendChild(title);['visible','locked'].forEach(property=>{const button=document.createElement('button');button.className='btn small';const state=layerState(cur.id)[key][property];button.textContent=property==='visible'?(state?'👁 显示':'🙈 隐藏'):(state?'🔒 已锁':'🔓 可编辑');button.setAttribute('aria-pressed',String(state));button.setAttribute('aria-label',label+'：'+button.textContent);button.onclick=()=>{snapshotArt();layerState(cur.id)[key][property]=!state;commitArt();renderLayerControls()};row.appendChild(button)});host.appendChild(row)});$('swapLayers').textContent=artFor(cur.id).layerOrder==='stickers-first'?'画笔在贴纸上方 · 点击交换':'贴纸在画笔上方 · 点击交换'}
$('swapLayers').onclick=()=>{snapshotArt();const a=artFor(cur.id);a.layerOrder=a.layerOrder==='stickers-first'?'paint-first':'stickers-first';commitArt();renderLayerControls()};
const baseSyncSticker=syncStickerControls;syncStickerControls=function(){baseSyncSticker();const t=cur&&artFor(cur.id).stickers.find(t=>t.id===selectedSticker);if(t)$('stickerRotation').value=t.rotation||0};
function editSticker(fn){if(!cur||layerState(cur.id).stickers.locked){toast('先解锁贴纸图层');return}const a=artFor(cur.id),t=a.stickers.find(t=>t.id===selectedSticker);if(!t)return;snapshotArt();fn(t,a);commitArt()}
$('stickerRotation').onchange=()=>editSticker(t=>t.rotation=+$('stickerRotation').value);
$('stickerFront').onclick=()=>editSticker((t,a)=>{a.stickers=a.stickers.filter(x=>x!==t);a.stickers.push(t)});$('stickerBack').onclick=()=>editSticker((t,a)=>{a.stickers=a.stickers.filter(x=>x!==t);a.stickers.unshift(t)});
const WORLD_DEFS=[{id:'forest',name:'动物森林',emoji:'🌳',color:'#dcf8db',match:/猫|兔|熊|鸟|蝶|森林|花|蜂|田野|树|野餐/,task:'为森林朋友设计一场彩虹野餐'},{id:'ocean',name:'海底王国',emoji:'🐳',color:'#d9f5ff',match:/海|鱼|鲸|章|蟹|船|岛|蛙|龟/,task:'给海底朋友画一座梦幻城堡'},{id:'space',name:'星空旅行',emoji:'🚀',color:'#ede1ff',match:/星|太空|火箭|机器人|宇宙|月|外星|飞碟|星际/,task:'创造你自己的星球和飞船'},{id:'sweet',name:'甜点乐园',emoji:'🧁',color:'#ffe2ed',match:/蛋糕|甜|冰|糖|水果|苹果|草莓|西瓜|甜甜圈/,task:'设计一个从没见过的彩虹甜点'},{id:'town',name:'彩虹小镇',emoji:'🏡',color:'#fff0cc',match:/小镇|屋|房|城|建筑|风车|塔|街|商店|学校|楼|桥/,task:'为小镇添一座你喜欢的房子'},{id:'story',name:'魔法故事',emoji:'🦄',color:'#f5ddff',match:/魔法|巫|龙|骑士|独角|公主|故事|仙|历险|勇|漫画/,task:'画一个魔法伙伴，给它编个故事'}];
function openWorlds(){const host=$('worldGrid');host.replaceChildren();WORLD_DEFS.forEach(w=>{const b=document.createElement('button');b.className='world-card';b.style.background=w.color;b.innerHTML='<span class="world-emoji" aria-hidden="true">'+w.emoji+'</span><h3>'+w.name+'</h3><p>'+w.task+'</p><small>自由探索 · 随时换世界</small>';b.onclick=()=>{pickWorld={...w,matches:p=>w.match.test(p.name)};pickPageLimit=12;onlyMyArt=false;const available=CATS.find(c=>LIST[c.id+ui.lv].some(p=>pickWorld.matches(p)));if(available)ui.cat=available.id;saveUi();renderPick();show('scr-pick')};host.appendChild(b)});show('scr-world')}
$('worldOpen').onclick=$('worldChange').onclick=openWorlds;$('worldBack').onclick=()=>{renderCover();show('scr-cover')};$('worldClear').onclick=()=>{pickWorld=null;pickPageLimit=12;renderPick()};
const baseRenderPick=renderPick;renderPick=function(){baseRenderPick();$('worldClear').hidden=!pickWorld;if(pickWorld){$('pickSay').textContent=pickWorld.emoji+' '+pickWorld.name+'：'+pickWorld.task+'。想画别的也可以！'}refreshMission()};
const baseRefreshMission=refreshMission;refreshMission=function(){baseRefreshMission();if(pickWorld)$('pickMission').textContent='✨ '+pickWorld.task+'（自由发挥）'};
$('morePictures').onclick=()=>{pickPageLimit+=12;renderPick()};$('moreGallery').onclick=()=>{galleryPageLimit+=12;renderGallery()};
const baseOpenPic=openPic;openPic=function(p){baseOpenPic(p);refreshArtist();renderLayerControls();renderQuickColors();$('saveStatus').textContent=hasArtwork(p.id)?'✓ 已恢复这幅作品，继续你的想象':'🖍 开始创作，作品会自动保存';const mission=$('studioMission');mission.replaceChildren();const img=document.createElement('img');img.src='assets/mascot-boy.webp';img.alt='小画家创作伙伴';img.width=45;img.height=68;const message=document.createElement('span');message.textContent='✨ '+(pickWorld?pickWorld.task:missions[missionIndex])+'。也可以画你自己的故事！';const skip=document.createElement('button');skip.className='btn small';skip.textContent='跳过任务';skip.onclick=()=>{mission.hidden=true};mission.hidden=false;mission.append(img,message,skip);save(KEY+'-last',p.id);refreshResume();regions.forEach((r,i)=>{r.setAttribute('tabindex','0');r.setAttribute('role','button');r.setAttribute('aria-label','填色区域 '+(i+1))});if(!load(KEY+'-guided',false))openGuide()};
$('canvas').addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key)||!e.target.matches('.r')||drawingLocked()||!['fill','erase'].includes(tool))return;e.preventDefault();const r=e.target,i=+r.dataset.i,previous=r.getAttribute('fill'),next=tool==='erase'?WHITE:color;if(previous!==next){redoStack=[];history.push([i,previous]);r.setAttribute('fill',next);saveState();progress();updateUndo()}});
function downloadData(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000)}
function albumData(){const ids=[...new Set([...Object.keys(store),...Object.keys(creative),...Object.keys(res)])].filter(id=>hasArtwork(id)||res[id]);return {format:'kidpaint-album',version:1,exportedAt:new Date().toISOString(),store:Object.fromEntries(ids.filter(id=>store[id]).map(id=>[id,store[id]])),creative:Object.fromEntries(ids.filter(id=>creative[id]).map(id=>[id,creative[id]])),stars:Object.fromEntries(ids.filter(id=>res[id]).map(id=>[id,res[id]])),last:load(KEY+'-last',null)}}
const numeric=(n,min,max)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
const safeColor=c=>typeof c==='string'&&/^#[0-9a-f]{6}$/i.test(c);
function validateAlbum(data){if(!data||data.format!=='kidpaint-album'||data.version!==1)throw Error('这不是 KidPaint 画册文件');const isMap=x=>x&&typeof x==='object'&&!Array.isArray(x);if(!isMap(data.store)||!isMap(data.creative)||!isMap(data.stars))throw Error('画册结构不完整');const ids=new Set([...Object.keys(data.store),...Object.keys(data.creative),...Object.keys(data.stars)]);if(ids.size>3000)throw Error('画册作品太多');const normalized={store:Object.create(null),creative:Object.create(null),stars:Object.create(null)};
 for(const id of ids){if(!/^blank-[a-z0-9-]+$/i.test(id)&&!LIST.findById(id))throw Error('画册中有无法识别的作品');const fills=data.store[id];if(fills!==undefined){if(!Array.isArray(fills)||fills.length>10000||!fills.every(safeColor))throw Error('作品颜色格式有误');normalized.store[id]=fills.slice()}
 const a=data.creative[id];if(a!==undefined){if(!isMap(a)||!Array.isArray(a.paths)||!Array.isArray(a.stickers)||a.paths.length>3000||a.stickers.length>400)throw Error('创作内容格式有误');const clean={title:typeof a.title==='string'?a.title.slice(0,80):'',paths:[],stickers:[]};if(a.artistName!==undefined){if(typeof a.artistName!=='string'||Array.from(a.artistName).length>20)throw Error('作品署名格式有误');clean.artistName=cleanArtistName(a.artistName)}if(a.showSignature!==undefined){if(typeof a.showSignature!=='boolean')throw Error('署名设置有误');clean.showSignature=a.showSignature}
 for(const p of a.paths){if(!p||typeof p.id!=='string'||!/^[a-z0-9-]+$/i.test(p.id)||typeof p.d!=='string'||p.d.length>200000||!/^M[0-9eE., +\-MmLlQqCcZz]+$/.test(p.d)||!safeColor(p.color)||!numeric(p.width,1,40)||!['brush','rainbow','gradient',undefined].includes(p.mode))throw Error('画笔数据有误');clean.paths.push({id:p.id,d:p.d,color:p.color,width:p.width,mode:p.mode||'brush'})}
 for(const t of a.stickers){if(!t||typeof t.id!=='string'||!/^[a-z0-9-]+$/i.test(t.id)||!stickerKeys.includes(t.key)||!numeric(t.x,-400,800)||!numeric(t.y,-400,800)||!numeric(t.size,20,200)||!numeric(t.rotation||0,-180,180))throw Error('贴纸数据有误');clean.stickers.push({id:t.id,key:t.key,x:t.x,y:t.y,size:t.size,rotation:t.rotation||0})}
 if(a.sourceId!==undefined){if(typeof a.sourceId!=='string'||!LIST.findById(a.sourceId))throw Error('作品来源有误');clean.sourceId=a.sourceId}if(a.colorSeed!==undefined){if(typeof a.colorSeed!=='string'||a.colorSeed.length>100||!/^[-a-z0-9]+$/i.test(a.colorSeed))throw Error('贴纸颜色来源有误');clean.colorSeed=a.colorSeed}if(a.layers){clean.layers={};for(const key of ['drawing','paint','stickers']){const l=a.layers[key];if(!l||typeof l.visible!=='boolean'||typeof l.locked!=='boolean')throw Error('图层数据有误');clean.layers[key]={visible:l.visible,locked:l.locked}}}if(a.layerOrder)clean.layerOrder=a.layerOrder==='stickers-first'?'stickers-first':'paint-first';if(safeColor(a.gradientColor))clean.gradientColor=a.gradientColor;normalized.creative[id]=clean}
 if(data.stars[id]!==undefined){if(!numeric(data.stars[id],0,3)||!Number.isInteger(data.stars[id]))throw Error('星星数据有误');normalized.stars[id]=data.stars[id]}
 }return normalized}
function mergeAlbum(incoming){const nextStore={...store},nextCreative=cloneData(creative),nextStars={...res};let imported=0;const ids=new Set([...Object.keys(incoming.store),...Object.keys(incoming.creative),...Object.keys(incoming.stars)]);for(const id of ids){let target=id;const exists=hasArtwork(id)||res[id];if(exists){let suffix=0;do{target='blank-import-'+Date.now().toString(36)+'-'+(++suffix)+'-'+hashStr(id).toString(36)}while(nextStore[target]||nextCreative[target]);const p=pictureById(id);const a=incoming.creative[id]||{paths:[],stickers:[],title:''};nextCreative[target]={...cloneData(a),title:(a.title||p?.name||'导入作品')+'（导入副本）',sourceId:a.sourceId||(!id.startsWith('blank-')?id:undefined),colorSeed:a.colorSeed||id}}if(incoming.store[id])nextStore[target]=incoming.store[id].slice();if(incoming.creative[id]&&!exists)nextCreative[target]=cloneData(incoming.creative[id]);if(incoming.stars[id])nextStars[target]=incoming.stars[id];imported++}
 if(!save(KEY+'-snapshot',{store:nextStore,creative:nextCreative,stars:nextStars}))throw Error('设备存储空间不足；原有画册没有更改');store=nextStore;creative=nextCreative;res=nextStars;persist();save(KEY+'-creative',creative);saveRes();paintHud();refreshResume();return imported}
$('backupExport').onclick=()=>{downloadData(new Blob([JSON.stringify(albumData())],{type:'application/json'}),'KidPaint-画册-'+new Date().toLocaleDateString('en-CA')+'.json');toast('画册已导出，可以在另一台设备导入')};
$('backupImport').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>25*1024*1024)throw Error('画册文件太大');const data=validateAlbum(JSON.parse(await file.text()));const count=mergeAlbum(data);renderGallery();toast('已导入 '+count+' 幅作品，原有作品保留')}catch(err){toast(err instanceof SyntaxError?'文件不是有效画册':err.message||'画册导入失败')}finally{e.target.value=''}};
// Imported copies retain the original outline while getting their own save ID.
const basePictureById=pictureById;pictureById=function(id){const p=basePictureById(id);if(p&&id.startsWith('blank-')&&creative[id]?.sourceId){const source=LIST.findById(creative[id].sourceId);if(source)return {...p,svg:source.svg,lv:source.lv,cat:source.cat}}return p};
function saveTitle(id,title){artFor(id).title=title;const ok=save(KEY+'-snapshot',{store,creative,stars:res});if(ok)save(KEY+'-creative',creative);else toast('名称没能保存，请导出画册备份')}
const originalGallery=renderGallery;renderGallery=function(){originalGallery();const ids=[...new Set([...Object.keys(store),...Object.keys(creative)])].filter(hasArtwork).reverse().slice(0,galleryPageLimit);[...$('artGallery').querySelectorAll('.gallery-title')].forEach((input,i)=>{const id=ids[i];input.onchange=()=>saveTitle(id,input.value.trim()||pictureById(id).name);const author=document.createElement('div');author.className='gallery-author';author.textContent=signatureFor(id)?'🖍 '+signatureFor(id)+' 的创作':'🖍 小画家的创作';input.after(author)})};
['deleteSticker','duplicateSticker'].forEach(id=>{const handler=$(id).onclick;$(id).onclick=()=>{if(layerState(cur.id).stickers.locked){toast('先解锁贴纸图层');return}handler()}});const sizeHandler=$('stickerSize').onchange;$('stickerSize').onchange=()=>{if(!layerState(cur.id).stickers.locked)sizeHandler()};
$('stickerTray').addEventListener('click',e=>{if(layerState(cur.id).stickers.locked){e.stopImmediatePropagation();e.preventDefault();toast('先解锁贴纸图层')}},true);
applyPreferences();refreshResume();refreshArtist();
if('serviceWorker' in navigator&&/^https?:$/.test(location.protocol)){navigator.serviceWorker.register('./sw.js').then(async reg=>{const worker=reg.installing||reg.waiting||reg.active;if(worker&&worker.state!=='activated')worker.addEventListener('statechange',()=>{if(worker.state==='activated')$('offlineStatus').textContent='✓ 已准备好：下次断网也能画画和听音乐'});else $('offlineStatus').textContent='✓ 已准备好：断网也能继续创作'}).catch(()=>$('offlineStatus').textContent='离线准备暂未完成，联网时仍可使用')}else $('offlineStatus').textContent='发布到网站后可准备离线使用';

$('featuredStart').onclick=()=>{ui.cat='featured';ui.lv=1;pickWorld=null;onlyMyArt=false;pickPageLimit=12;saveUi();renderPick();show('scr-pick')};
